.scan-image:
  stage: scan-image
  allow_failure: true
  needs: [ build-image, zarf-sbom]
  cache: []
  variables:
    GIT_STRATEGY: none
    CONTAINER_SCAN_REPORT: ${ARTIFACT_FOLDER}/scan-image/report.json
    FORMATTED_REPORT: ${ARTIFACT_FOLDER}/scan-image/report.txt
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_FOLDER}/scan-image/"
 
  before_script:
    - mkdir -p ${ARTIFACT_FOLDER}/scan-image/