name: Publish Zarf Package

on:
  push:
    branches: chore-zarf-pkg-images

permissions:
  contents: read
  packages: write
  id-token: write

jobs: 
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push zarf image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/defenseunicorns/swf-pipeline-templates/zarf:v0.31.3
          context: dockerfiles
          file: dockerfiles/zarf.Dockerfile
          platforms: linux/amd64

      - name: Build and push trivy image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/defenseunicorns/swf-pipeline-templates/trivy:0.48.0-with-db
          context: dockerfiles
          file: dockerfiles/trivy.Dockerfile
          platforms: linux/amd64

      - name: Build and push grype image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/defenseunicorns/swf-pipeline-templates/grype:v0.73.4-with-db
          context: dockerfiles
          file: dockerfiles/grype.Dockerfile
          platforms: linux/amd64
